#!/usr/bin/env node

/**
 * Interactive setup wizard for the Team Wish Board.
 * Run with:  npm run setup
 */

import { createInterface } from "node:readline";
import { writeFileSync, existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";

const rl = createInterface({ input: process.stdin, output: process.stdout });
const ask = (q) => new Promise((res) => rl.question(q, res));

const ENV_FILE = resolve(process.cwd(), ".env.local");

function banner() {
  console.log();
  console.log("╔══════════════════════════════════════════════╗");
  console.log("║      Team Wish Board — Setup Wizard         ║");
  console.log("╚══════════════════════════════════════════════╝");
  console.log();
}

async function main() {
  banner();

  if (existsSync(ENV_FILE)) {
    const overwrite = await ask(
      "  .env.local already exists. Overwrite? (y/N) "
    );
    if (overwrite.trim().toLowerCase() !== "y") {
      console.log("\n  Aborted. Your existing .env.local was not changed.\n");
      rl.close();
      return;
    }
    console.log();
  }

  // ── 1. Person's name ──────────────────────────────────────
  const personName = (
    await ask("  Person's name (who is being celebrated): ")
  ).trim();
  if (!personName) {
    console.log("\n  Name is required. Please re-run the wizard.\n");
    rl.close();
    return;
  }

  // ── 2. Team name ──────────────────────────────────────────
  const teamName = (
    await ask("  Team name: ")
  ).trim() || "my-team";

  // ── 3. Occasion type ──────────────────────────────────────
  console.log();
  console.log("  Occasion types:");
  console.log("    1) farewell");
  console.log("    2) birthday");
  console.log("    3) anniversary");
  console.log("    4) custom");
  const occasionChoice = (await ask("  Choose occasion type [1-4] (default 1): ")).trim();
  const occasionMap = { "1": "farewell", "2": "birthday", "3": "anniversary", "4": "custom" };
  const occasionType = occasionMap[occasionChoice] || "farewell";

  // ── 4. Occasion date ──────────────────────────────────────
  console.log();
  console.log("  Enter the occasion date in ISO 8601 format.");
  console.log("  Examples: 2026-06-15T23:59:59Z  or  2026-12-25T00:00:00Z");
  const occasionDate = (
    await ask("  Occasion date: ")
  ).trim() || "2026-12-31T23:59:59Z";

  // ── 5. Theme ──────────────────────────────────────────────
  console.log();
  console.log("  Theme options:");
  console.log("    1) light  — clean Atlassian Design System look");
  console.log("    2) dark   — dark mode with starfield + violet accents");
  const themeChoice = (await ask("  Choose theme [1-2] (default 1): ")).trim();
  const uiVariant = themeChoice === "2" ? "dark" : "";

  // ── 6. Optional: board title override ─────────────────────
  console.log();
  const autoTitle = {
    farewell: `The ${personName} Effect`,
    birthday: `Happy Birthday, ${personName}!`,
    anniversary: `Celebrating ${personName}!`,
    custom: `Wishes for ${personName}`,
  }[occasionType];
  console.log(`  Auto-generated title: "${autoTitle}"`);
  const customTitle = (
    await ask("  Custom board title (press Enter to keep auto): ")
  ).trim();

  // ── 7. GIPHY API key ─────────────────────────────────────
  console.log();
  console.log("  GIPHY enables the GIF search tab in the wish modal.");
  console.log("  Get a free key at: https://developers.giphy.com/");
  const giphyKey = (
    await ask("  GIPHY API key (press Enter to skip): ")
  ).trim();

  // ── 8. Database ───────────────────────────────────────────
  console.log();
  console.log("  The wish board stores wishes in a Postgres database.");
  console.log("  Create a free database at: https://neon.tech");
  console.log("  Use the pooled (serverless) connection string.");
  const dbUrl = (
    await ask("  DATABASE_URL (press Enter to configure later): ")
  ).trim();

  // ── 9. Vercel Blob ────────────────────────────────────────
  console.log();
  console.log("  Vercel Blob is used for image uploads.");
  console.log("  This token is set automatically when you add Blob");
  console.log("  in the Vercel dashboard (Storage → Add → Blob).");
  const blobToken = (
    await ask("  BLOB_READ_WRITE_TOKEN (press Enter to configure later): ")
  ).trim();

  // ── Generate .env.local ───────────────────────────────────
  const lines = [
    `# Generated by setup wizard — ${new Date().toISOString()}`,
    "",
    `NEXT_PUBLIC_PERSON_NAME=${personName}`,
    `NEXT_PUBLIC_TEAM_NAME=${teamName}`,
    `NEXT_PUBLIC_OCCASION_DATE=${occasionDate}`,
    `NEXT_PUBLIC_OCCASION_TYPE=${occasionType}`,
  ];

  if (customTitle) {
    lines.push(`NEXT_PUBLIC_BOARD_TITLE=${customTitle}`);
  }

  if (uiVariant) {
    lines.push(`NEXT_PUBLIC_UI_VARIANT=${uiVariant}`);
  }

  lines.push("");

  if (giphyKey) {
    lines.push(`GIPHY_API_KEY=${giphyKey}`);
  } else {
    lines.push("# GIPHY_API_KEY=");
  }

  lines.push("");

  if (dbUrl) {
    lines.push(`DATABASE_URL=${dbUrl}`);
  } else {
    lines.push("# DATABASE_URL=postgres://...");
  }

  if (blobToken) {
    lines.push(`BLOB_READ_WRITE_TOKEN=${blobToken}`);
  } else {
    lines.push("# BLOB_READ_WRITE_TOKEN=");
  }

  lines.push("");
  writeFileSync(ENV_FILE, lines.join("\n"), "utf-8");

  // ── Summary ───────────────────────────────────────────────
  console.log();
  console.log("  ✅ .env.local created successfully!");
  console.log();
  console.log("  ┌─────────────────────────────────────────────┐");
  console.log(`  │  Person:   ${personName}`);
  console.log(`  │  Team:     ${teamName}`);
  console.log(`  │  Occasion: ${occasionType}`);
  console.log(`  │  Date:     ${occasionDate}`);
  console.log(`  │  Theme:    ${uiVariant || "light"}`);
  console.log(`  │  Title:    ${customTitle || autoTitle}`);
  console.log(`  │  GIPHY:    ${giphyKey ? "configured" : "not set (GIF tab disabled)"}`);
  console.log(`  │  Database: ${dbUrl ? "configured" : "not set yet"}`);
  console.log(`  │  Blob:     ${blobToken ? "configured" : "not set yet"}`);
  console.log("  └─────────────────────────────────────────────┘");
  console.log();

  // ── Next steps ────────────────────────────────────────────
  console.log("  Next steps:");
  console.log("  ─────────────────────────────────────────────");
  if (!dbUrl) {
    console.log("  1. Create a free Postgres database at https://neon.tech");
    console.log("     and add DATABASE_URL to .env.local");
    console.log("  2. Run the table creation SQL:");
    console.log("     scripts/init-wishes-table.sql");
  } else {
    console.log("  1. Run the table creation SQL in your Neon SQL Editor:");
    console.log("     scripts/init-wishes-table.sql");
  }
  console.log();
  console.log("  Then start the dev server:");
  console.log("    npm run dev");
  console.log();

  rl.close();
}

main().catch((err) => {
  console.error(err);
  rl.close();
  process.exit(1);
});
